name: Build and Push Docker Images

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Install Docker Compose
        uses: KengoTODA/actions-setup-docker-compose@v1
        with:
          version: "2.14.2"
          env:
          POSTGRES_USERNAME: ${{ secrets.POSTGRES_USERNAME }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          AWS_BUCKET: ${{ env.AWS_BUCKET }}
          AWS_PROFILE: ${{ env.AWS_PROFILE }}
          AWS_REGION: ${{ env.AWS_REGION }}
          URL: ${{ env.URL }}
        run: |
          docker-compose -f docker-compose-build.yml build --parallel \
            --build-arg POSTGRES_USERNAME=${POSTGRES_USERNAME} \
            --build-arg POSTGRES_PASSWORD=${POSTGRES_PASSWORD} \
            --build-arg POSTGRES_HOST=${POSTGRES_HOST} \
            --build-arg POSTGRES_DB=${POSTGRES_DB} \
            --build-arg JWT_SECRET=${JWT_SECRET} \
            --build-arg AWS_BUCKET=${AWS_BUCKET} \
            --build-arg AWS_PROFILE=${AWS_PROFILE} \
            --build-arg AWS_REGION=${AWS_REGION} \
            --build-arg URL=${URL} \
          docker-compose push
